### ISSUE TITLE
Release 2.3.2 has wrong module.json

### ISSUE THREAD

**Issue by farling42** [League-of-Foundry-Developers/fvtt-module-theatre#119]
The latest version of module.json in the base directory has been updated for V10, but the version of module.json in release 2.3.2 is still the V9 version. This means that there are 4 warnings produced when Foundry starts.

**Comment by megahead11** [comment]
Weird. I could've sworn that push had the .json update with it. I'll give it a look and see if it just released incorrectly.

**Comment by megahead11** [comment]
Ahh, my bad. It seems the last batch of updates weren't pushed recently. I have released a new version as v2.4.0, but it might need some new issues if anything pops up with the last batch of changes.
