### ISSUE TITLE
Module doesn't work on Foundry v11

### ISSUE THREAD

**Issue by ZwS** [League-of-Foundry-Developers/fvtt-module-theatre#121]
There is no particular error messages in the console, but once module is enabled screen become black.

**Comment by action-jay** [comment]
Caught this too. There is an error message once you try to add a character to the stage:

<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/theatre/app/js/Theatre.js:2949" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">Theatre.js:2949</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color)  !important;">Uncaught <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: undefined. Cannot read properties of undefined (reading 'shared')
[Detected 1 package: theatre]
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Theatre._addSpritesToPixi (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/theatre/app/js/Theatre.js:2949:28" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">Theatre.js:2949:28</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Theatre.stageInsertById (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/theatre/app/js/Theatre.js:3078:8" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">Theatre.js:3078:8</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Theatre.addToNavBar (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/theatre/app/js/Theatre.js:8196:20" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">Theatre.js:8196:20</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.callback (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/theatre/app/js/theatre_main.js:507:34" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">theatre_main.js:507:34</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at #onClickItem (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/scripts/foundry.js:64006:11" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">foundry.js:64006:11</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at HTMLElement.dispatch (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/scripts/jquery.min.js:2:43184" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">jquery.min.js:2:43184</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at y.handle (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/scripts/jquery.min.js:2:41168" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">jquery.min.js:2:41168</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | _addSpritesToPixi | @ | Theatre.js:2949
-- | -- | -- | --
  | stageInsertById | @ | Theatre.js:3078
  | addToNavBar | @ | Theatre.js:8196
  | callback | @ | theatre_main.js:507
  | #onClickItem | @ | foundry.js:64006
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2

</span></div>
</body>
</html>

**Comment by rukaiko** [comment]
Yes, same problem here. There is no way to make it work?

**Comment by SourceRyan** [comment]
Foundry v11 updated to use Pixi.JS v7, which has replaced PIXI.Loader. It looks like the module needs to be [updated to use Assets instead](https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#-replaces-loader-with-assets).

**Comment by megahead11** [comment]
Indeed. The japanese foundry community is scrounging up funds to commission updates and fixes for v11, but without outside support, it is difficult. 

For other's information, I simply maintain the repo for pulls requests and such, but we haven't had someone updating the module for a while. The last update for v9 to v10 was pretty big for the module but this one might be a big breaker because of the further pixi changes, and the weight of the old cold is showing.

**Comment by Nolt-Appley** [comment]
How much would it cost to commission this module to be updated properly?

**Comment by megahead11** [comment]
Last time there was an update, it was about 200+ USD, but it could be different this time. Brother Sharp (on discord) is the main person funding the updates through his own money and the Japanese foundry patreon. No definites yet, but I would contact them in case you wanted to contribute (Brother Sharp#6921)

**Comment by strongpauly** [comment]
I've had a got at converting to use PIXI.Assets with the open PR.  Still not working, but I thought it was worth a punt.

**Comment by megahead11** [comment]
> I've had a go at converting to use PIXI.Assets with the open PR. Still not working, but I thought it was worth a punt.

What happened? Does it still break the canvas?

**Comment by strongpauly** [comment]
It now prevents scenes from being loaded, without any discernible error - although the Theatre itself seemed to work.  I'll try and have another look soon.

**Comment by strongpauly** [comment]
The canvas wasn't broken, it was just hidden behind the Theatre canvas.  Changing from passing `transparent: true` to `backgroundAlpha: 0` appears to have fixed it.

**Comment by rukaiko** [comment]
May I ask where did you change those options?

**Comment by megahead11** [comment]
I will verify if this works when i get home. If it does, I'll merge the PR with a bump for version compatibility and push a release.

**Comment by megahead11** [comment]
> The canvas wasn't broken, it was just hidden behind the Theatre canvas. Changing from passing `transparent: true` to `backgroundAlpha: 0` appears to have fixed it.

I've given it a try with the PR fixes, and the module is useable enough for v11, but has a minor bug from what I can see (could be unrelated to the PIXI.Assets change). It seems if you unstage an actor that had an emote active, then restage it, it'll toss this error: 

![image](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/21242682/3b542caf-be64-4f74-9c21-84b5246ae3b9)

Kind of a minor bug,  as turning off the emote and restaging will fix it, but I know someone is likely to bring it up. 

Aside from this, I think this should suffice for v11 compatibility with this bug aside. If you think you can do anything about that, let me know, otherwise I can just merge the PR as is.

**Comment by strongpauly** [comment]
> May I ask where did you change those options?

Inside `_initTheatreDockCanvas` where it creates the `PIXI.Application`.
