### ISSUE TITLE
V11: Unstaging an actor with an active emote and restaging causes issues

### ISSUE THREAD

**Issue by megahead11** [League-of-Foundry-Developers/fvtt-module-theatre#124]
It seems if you unstage an actor that had an emote active, then restage it, it'll toss this error (and the actor will not show up on stage): 

![image](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/21242682/3b542caf-be64-4f74-9c21-84b5246ae3b9)

The actor will not appear on stage, but if you disable the emote then restage, it will behave as normal.

**Comment by farling42** [comment]
Line 4438 of Theatre.js is missing an "await", it should read:

```
		let texture = await PIXI.Assets.load(resTarget.path);
```
