### ISSUE TITLE
Update for V11 functionality?

### ISSUE THREAD

**Issue by HarrisonMAD** [League-of-Foundry-Developers/fvtt-module-theatre#126]
Module will enable in V11 but:

Enabling the module prevents scenes from loading (no error in console, just blacked out scene)

**Comment by megahead11** [comment]
I haven't officially released the v11 compatability. The latest version of the repo should make it useable in v11, but there are a couple of bugs I'm hoping will get fixed before I can officially declare v11 support.

**Comment by megahead11** [comment]
v2.5.0+ should fix compatibility issues, for the time being. Let us know if there are new issues preventing it from working c:
