### ISSUE TITLE
incompatibility with Combat Utility Belt "Hide NPC names" & suggestion

### ISSUE THREAD

**Issue by PaukPeck** [League-of-Foundry-Developers/fvtt-module-theatre#127]
Hello, I absolutely love that module but I must turn it off when i don't want my players to see the real name of my NPCs

Also, it would be awesome to have the possibility to make appear the image of a token instead of the avatar of the character when you are using generic npc's with random images (*.jpg)

Thanks for the good work, anyway

**Comment by megahead11** [comment]
Does the theatre settings for the character not work? You should be able to set a different name for the character being staged using that.

**Comment by PaukPeck** [comment]
No problem to set a different name when a character is staged, it works perfectly. 
It's just that Combat Utility Belt allows me to hide the real character name in the chat or in the combat tracker, but it doesn't work when Theatre Inserts is enabled

**Comment by megahead11** [comment]
If you go in and edit line 225 of theatre_main.js and comment out ``actor: null,`` as ``//actor: null,`` (or delete it, that works too), does it work?

**Comment by PaukPeck** [comment]
I'm on the Forge with Foundry v10 and I don't understand well how to custom a module and use only this version in the Forge but i will try your suggestion.
By the way, i noticed that Combat Utility Belt and Theatre Inserts work perfectly well together in my local Foundry in V11

**Comment by PaukPeck** [comment]
Resolved ! As I play in v10, i had just to install version 2.2.2 to have it work perfectly.
Sorry for the loss of time and thank you for your help !

**Comment by p4535992** [comment]
The ticket can be closed
