### ISSUE TITLE
Can't install on V11 from Foundry "Install Module" page

### ISSUE THREAD

**Issue by farling42** [League-of-Foundry-Developers/fvtt-module-theatre#130]
The link on the Foundry module web site is still pointing to 2.2.2, which means it won't install on V11

**Comment by farling42** [comment]
Also, the verified flag is still set to 10

**Comment by megahead11** [comment]
I think I need to poke someone to update it; I'm not sure why, but I think it's been like that for a while.

**Comment by Artemisthemp** [comment]
I was able to install on v11 using the 2.5.1 Module json - https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/releases/download/v2.5.1/module.json

Do the file is mark as v10 as max compatible.

**Comment by farling42** [comment]
Yes, I could install from the URL in the readme. It is only the link on the foundry package manager web site which needs changing so that it can be installed by entering the name and finding it in Foundry's module listing.

**Comment by megahead11** [comment]
Latest should be available for now. I may have a couple extra updates to push in the near future depending on things.
