### ISSUE TITLE
[Bug] Theatre Inserts and JB2A/Automated Animations

### ISSUE THREAD

**Issue by enalis** [League-of-Foundry-Developers/fvtt-module-theatre#142]
Hello!

In my PF1 game recently we had our animations cease working, according to Find the Culprit Theatre was the issue. In a seperate game using only JB2A and the associated required modules (Automated Animations, Sequencer, Socket, and FX) only the issue presisted with animations not working unless Theatre was disabled.

PF1 using Forge with Foundry V11 build 307.

**Comment by p4535992** [comment]
can you click f12 and see if there is any error on the web console ?

**Comment by enalis** [comment]
Not sure exactly what I am looking for but this is what I get when I filter for errors in my test game. Test game only has the following modules active:

Automated Animations, FXMaster, JB2A Pateron Complete Collection, Sequencer, Socketlib, and THeatre Inserts. WOrks perfectly when TI is disabled.

Foundry VTT | Before DOMContentLoaded [foundry.js:90983:9](https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js)
downloadable font: kern: Kerning pairs are not sorted (font-family: "Western" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/WEST.ttf
downloadable font: Table discarded (font-family: "Western" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/WEST.ttf
Foundry VTT | Loading 43 Assets [foundry.js:29202:13](https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js)
PixiJS Deprecation Warning: Setting interactive is deprecated, use eventMode = 'none'/'passive'/'auto'/'static'/'dynamic' instead.
Deprecated since v7.2.0 [index.mjs:1:32](https://enalisnailo-test-bench.forge-vtt.com/packages/constants/lib/index.mjs)
PixiJS Deprecation Warning: utils.rgb2hex is deprecated, use Color#toNumber instead
Deprecated since v7.2.0 [index.mjs:1:32](https://enalisnailo-test-bench.forge-vtt.com/packages/constants/lib/index.mjs)
TypeError: Error thrown in hooked function '' for hook 'renderItemSheet'. data.entity is undefined
    bind https://assets.forge-vtt.com/bazaar/modules/automated-jb2a-animations/0.3.28/src/item-sheet-handlers/item-sheet-config.js:32
    <anonymous> https://assets.forge-vtt.com/bazaar/modules/automated-jb2a-animations/0.3.28/src/autoAnimations.js:209
    #call https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:730
    callAll https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:687
    _render https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:5777
[foundry.js:753:30](https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js)
    onError https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:753
    #call https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:734
    callAll https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:687
    _render https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:5777
TypeError: Error thrown in hooked function '' for hook 'renderItemSheet'. data.entity is undefined
    bind https://assets.forge-vtt.com/bazaar/modules/automated-jb2a-animations/0.3.28/src/item-sheet-handlers/item-sheet-config.js:32
    <anonymous> https://assets.forge-vtt.com/bazaar/modules/automated-jb2a-animations/0.3.28/src/autoAnimations.js:209
    #call https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:730
    callAll https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:687
    _render https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:5777
[foundry.js:753:30](https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js)
TypeError: Error thrown in hooked function '' for hook 'renderItemSheet'. data.entity is undefined
    bind https://assets.forge-vtt.com/bazaar/modules/automated-jb2a-animations/0.3.28/src/item-sheet-handlers/item-sheet-config.js:32
    <anonymous> https://assets.forge-vtt.com/bazaar/modules/automated-jb2a-animations/0.3.28/src/autoAnimations.js:209
    #call https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:730
    callAll https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:687
    _render https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:5777
[foundry.js:753:30](https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js)
TypeError: Error thrown in hooked function '' for hook 'renderItemSheet'. data.entity is undefined
    bind https://assets.forge-vtt.com/bazaar/modules/automated-jb2a-animations/0.3.28/src/item-sheet-handlers/item-sheet-config.js:32
    <anonymous> https://assets.forge-vtt.com/bazaar/modules/automated-jb2a-animations/0.3.28/src/autoAnimations.js:209
    #call https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:730
    callAll https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:687
    _render https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js:5777
[foundry.js:753:30](https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js)
Uncaught TypeError: data.origin is undefined
    #handleMouseMove foundry.js:31913
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerMove earcut.js:128
    mapEvent earcut.js:128
    onPointerMove earcut.js:128
[foundry.js:31913:18](https://enalisnailo-test-bench.forge-vtt.com/scripts/foundry.js)
    #handleMouseMove foundry.js:31913
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerMove earcut.js:128
    mapEvent earcut.js:128
    onPointerMove earcut.js:128

**Comment by enalis** [comment]
Issue still persists.

**Comment by Zepppi** [comment]
Just chiming in to say I also have the exact same problem running on a pf1e system through Forge. I was able to re-create the issue with only a minimal amount of mods active to rule out any complicated interactions. I only have the following active.

Automated Animations
JB2A - Patreon Complete Collection
Sequencer
socketlib
The Forge
Theater Inserts

**Comment by enalis** [comment]
Figured out how to use F12 a bit better. Put it on errors filter and got this. My test bench is using the same minimal modules as Zeppi. Also PF1


downloadable font: hdmx: the table should not be present when bit 2 and 4 of the head->flags are not set (font-family: "StoneHenge" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/stonehen.ttf
downloadable font: Table discarded (font-family: "StoneHenge" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/stonehen.ttf
downloadable font: hdmx: the table should not be present when bit 2 and 4 of the head->flags are not set (font-family: "StampAct" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/STAMPACT.ttf
downloadable font: Table discarded (font-family: "StampAct" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/STAMPACT.ttf
downloadable font: hdmx: the table should not be present when bit 2 and 4 of the head->flags are not set (font-family: "TrashHand" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/TrashHand.ttf
downloadable font: Table discarded (font-family: "TrashHand" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/TrashHand.ttf
downloadable font: hdmx: the table should not be present when bit 2 and 4 of the head->flags are not set (font-family: "Yikes" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/YIKES!.ttf
downloadable font: Table discarded (font-family: "Yikes" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/YIKES!.ttf
downloadable font: kern: Kerning pairs are not sorted (font-family: "Western" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/WEST.ttf
downloadable font: Table discarded (font-family: "Western" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/WEST.ttf
downloadable font: kern: Kerning pairs are not sorted (font-family: "ArabDances" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/ArabDances.ttf
downloadable font: Table discarded (font-family: "ArabDances" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/theatre/2.5.3/app/graphics/fonts/en/ArabDances.ttf
Foundry Virtual Tabletop requires a minimum screen resolution of 1024px by 700px or greater. Your display currently has an effective resolution of 1920px by 128px, as a result many features of the software may not work properly.

**Comment by p4535992** [comment]
the issue still persist with 2.6.0 ?

**Comment by Zepppi** [comment]
Unfortunately yes it does.

**Comment by enalis** [comment]
Just tried with 2.6 as well, same thing.

**Comment by enalis** [comment]
Updated to 2.6.1. Animations still broken.

**Comment by Zepppi** [comment]
Same sadly.

**Comment by enalis** [comment]
Updated to 2.7.4 - issue remains.

**Comment by Zepppi** [comment]
I talked with JB2A's people about it a while ago and they suggested it might be something unique to how Forge handles modules. I am not sure if that helps or not.

**Comment by enalis** [comment]
Sorry its been a hot minute, but I did get this updated to 2.8. I did what Zeppi suggested and tested it on Foundry rather than forge and came to the same results.

If I want to put a bounty on this how do I go about doing that?

**Comment by megahead11** [comment]
You would have to make a bounty through the Foundry League's discord: 
https://discord.gg/w8Mp2X5j (IDK how long this link will last)

**Comment by enalis** [comment]
> You would have to make a bounty through the Foundry League's discord: https://discord.gg/w8Mp2X5j (IDK how long this link will last)

Thank you very much, I have posted a bounty for this.

**Comment by elizeuangelo** [comment]
This should be fixed on https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/pull/164
But please someone more familiar with the module review it before merging.
