### ISSUE TITLE
[BUG] Theatre Insert config in Actor Header not opening

### ISSUE THREAD

**Issue by TheNittles** [League-of-Foundry-Developers/fvtt-module-theatre#150]
**Module Version:** v2.6.1

**Describe the bug**
When I click the button in the header of an actor's sheet in my game to open the config for their Theatre Insert, nothing happens.

**To Reproduce**
1. Open an actor's sheet
2. Click the header button

**Expected behavior**
The config page to open

**Screenshots**
![image](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/137443034/8121b781-cf3b-4f02-a697-c63939fbd2dc)

**Browser:**
 Google Chrome

**Foundry Version:** 
v11.313

**Game System:** 
D&D 4e

**Additional context**
The screenshot I took has all my modules enabled, but the same behavior happens with nothing except Theatre Inserts enabled.
The last version of the module where the button worked (and the one I'm using for now) is 2.5.3

**Comment by KoboldCatgirl** [comment]
I am also experiencing this bug on PF2e, even if all other modules are disabled. I am using Theatre Inserts v2.6.1 and Foundry v11.3.0.9, and I'm using PF2e.
