### ISSUE TITLE
Module prevents dialog windows from being activated from Chat [PF2E] [BUG]

### ISSUE THREAD

**Issue by VoltasPistol** [League-of-Foundry-Developers/fvtt-module-theatre#161]
Hi!

Sorry, I couldn't find an "enable debugging" anywhere, but I did disable all the other modules I have installed, then activated libwrapper and I could not reproduce the bug, and then I enabled theater inserts and I was able to reproduce the bug.

![Screenshot 2024-01-14 125549](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/156613871/5a232e55-609f-48ee-8b44-ea99b3184b9d)

![Screenshot 2024-01-14 125715](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/156613871/5ef14614-d0ca-4158-bfab-dd0f6280964b)

Basically, when I have theater inserts activated, any type of clickable button of that type in chat, where you would expect some kind of dialog window to pop up, does nothing.  It highlights in red when mouseovered, but you can click and click and click and nothing happens.

There are my theater inserts & libwrapper settings:

![Screenshot 2024-01-14 125932](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/156613871/93e21edb-73ef-4930-8fa0-2d030334d503)

![Screenshot 2024-01-14 130106](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/156613871/7ca284f0-89e5-4462-ba2f-2f00d534af40)

![Screenshot 2024-01-14 130546](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/156613871/da794cee-2cbf-4ef0-a639-6835810dc374)

I hope that's enough information to figure out what went wrong, but if you can tell me where that dang debugging button is, I'd be happy to share that too.  <3

Thank you for all your hard work!  ^_^

**Module Version:** v0.0.0

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser:**
 - 

**Foundry Version:** 

**Game System:** 

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by VoltasPistol** [comment]
Oh!!  And the little circular "undo" button COMPLETELY VANISHES.  I thought that was weird too.


![Screenshot 2024-01-14 134433](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/156613871/09599777-0f14-4079-a624-8e631a5a387b)

**Comment by megahead11** [comment]
Module version is v0.0.0.0?
That doesnt seem right. What is the actual version? Are you using the latest version available and are you on forge?

**Comment by VoltasPistol** [comment]
I'm sorry, where are you seeing v0.0.0.0?  I don't see where it says that on any of the screenshots?  I'm very confused about where you got the impression that I told you I was using an impossible version.... v0.0.0.0 is impossible, right?  

Are you trying to ask for this?

![Screenshot 2024-01-14 192751](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/156613871/f37f6496-df0c-4bbf-80db-7a6c90d3a6de)

Please, in the future, **please just ask** instead of making up things to confuse users who are already struggling.  I can barely wrap my head around this as it is and I struggled just trying to set up an account on github, it's all so confusing and I have no idea how any of this website works.

Yes, I'm using the latest version of everything, I think, but I don't know what "Forge" is"??  Is it another joke?  I'm sorry I'm so confused.

**Comment by megahead11** [comment]
Sorry, I didn't mean to confuse you. You had the "default" template attached which didn't have the version included. 
![image](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/21242682/aaad8b76-def8-4da0-8258-346ed046c760)

Forge is a remote hosting site, but given that you didn't know what it was, I am safe to assume you aren't using it. Where it says to install the modules via manifest, please use this link https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/releases/download/v2.8.0/module.json

**Comment by megahead11** [comment]
To further clarify, some users have not been able to receive the most up to date version. Using that manual install is necessary.

**Comment by megahead11** [comment]
If installing via the manifest is not working, you can also try installing it using this link: https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/releases/tag/v2.8.0 This is assuming you are hosting it on your own PC.
Go down to where it says "Module.zip" and download the .zip file. Then, find your foundry's installation directory (for most people, it's in \User\AppData\Local\FoundryVTT\Data\modules on windows), then unzip the folder into its own directory there (name it "theatre" exactly, lower case).

**Comment by VoltasPistol** [comment]
Yes, I've been installing from the manifest.

![Screenshot 2024-01-15 104836](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/156613871/caad9795-7f8e-4193-ac51-eb56d34a3c66)
![Screenshot 2024-01-15 104910](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/156613871/870e920a-cfc1-4c1c-95ae-03dff999b698)

But I installed from the .json link in the github page you linked and now it does seem to be working again.  

Thank you for your kindness and patience as I struggle through this but just one more question?

Is the .json github page link that made it work a permanent fix (as in, I will not need to worry about updating it) or will I have to reinstall from the manifest link on Foundry's website when a new version of Foundry drops?

**Comment by megahead11** [comment]
As far as I'm aware, this is a permanent fix. You should not need to update it beyond the manifest link. However, foundry updates can be unpredictable, and new problems could arise that comes with new updates. I recommend backing up your worlds before any major foundry update or waiting for compatibility, as it is always a possibility something changes that may cause issues. Glad to hear that the .json fixed it! :)
