### ISSUE TITLE
[BUG] Auto-quotes missing on v2.8.1

### ISSUE THREAD

**Issue by Shaeress** [League-of-Foundry-Developers/fvtt-module-theatre#169]
**Module Version:** v2.8.1
in Savage Worlds ruleset

When using the auto-quotes feature, no matter what style of quotes is chosen, the quotes show an error message in the theatre text box instead, as shown in the screenshot.

![image](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/assets/80639899/5bcdce7f-638a-4b29-a6b1-a632335e09c3)

**Comment by megahead11** [comment]
Solved in v2.9.1.
