### ISSUE TITLE
Bug changing the name's font, and a request for add all to stage

### ISSUE THREAD

**Issue by smoothingplane** [League-of-Foundry-Developers/fvtt-module-theatre#23]
I noticed a bug when I change the font of the names, theater set the "theater bar display mode" to "text box style" (even if it still indicates the one selected previously, clear box style in my case), you have to set "text box style" and subsequently reset the style you wanted (clear box style in my case), it also happens with changing the font size.

Also is it possible to add a button to add all player characters to the stage?

**Comment by megahead11** [comment]
I've actually experienced this bug in testing, I believe I have an idea of why it might be based on some leftover code.
Were you able to reset the the theatre box style successfully?

I believe a refresh may also fix it, as it appears to be a minor visual bug.

As for adding a request for all stage, can you log this as a separate issue?

**Comment by megahead11** [comment]
The style change issue is fixed in v1.16.2... I think!
