### ISSUE TITLE
[Feature] Narrator text font and size settings

### ISSUE THREAD

**Issue by bcartwright** [League-of-Foundry-Developers/fvtt-module-theatre#26]
Now that we have the ability to change character name font and size, I want to make the narrator font match!

**Comment by megahead11** [comment]
Isn't this a feature that's already in Theatre? I'm assuming you're using Narrator mode for the text.
You should be able to change the font the same way you do for the chat/text boxes, using the emote icon menu.

**Comment by bcartwright** [comment]
Ah, yep that's what I was looking for! Thanks!
