### ISSUE TITLE
Compatibility beyond 0.73

### ISSUE THREAD

**Issue by enalis** [League-of-Foundry-Developers/fvtt-module-theatre#28]
It would appear that any build post 0.73 seems to be not working. The character portrait does not come up nor does text appear but the black bar and stage still do
![image](https://user-images.githubusercontent.com/83319486/116327830-37016e00-a78d-11eb-8a73-66167a06e830.png)

**Comment by strongpauly** [comment]
Works for me on 0.7.9.  Maybe disable some of your other modules to see if there are conflicts?  Are there errors in the console?

**Comment by enalis** [comment]
found the issue- was a compatibility error with an older version of a
different module.
