### ISSUE TITLE
Compatibility Issue with Perfect Vision

### ISSUE THREAD

**Issue by VentusCursor** [League-of-Foundry-Developers/fvtt-module-theatre#29]
When the Perfect Vision module is active, half the stage gets cut off. The "stage boxes" are there, but no actor appears. 
![Theatre Issue](https://user-images.githubusercontent.com/83527705/116802806-50504480-ab16-11eb-8ba3-effb4c2f1e87.png)

**Comment by cbgh2021** [comment]
I'm also getting this problem.

**Comment by NRschwier** [comment]
Does anyone know of a good solution besides disabling Perfect Vision?
