### ISSUE TITLE
README Improvements

### ISSUE THREAD

**Issue by anthonyronda** [League-of-Foundry-Developers/fvtt-module-theatre#31]
This project will be included in the League's student initiative. I hope to beautify this README to entice students to make contributions.

- [ ] Screenshots/Video
- [ ] Pull the usage documentation from GitLab and make a GH Wiki
- [ ] Add CONTRIBUTING
- [ ] Remove line "original author does not support FVTT..."

**Comment by anthonyronda** [comment]
Is there a reason the "extract ZIP to the modules directory" method of installation is listed? It's not a recommended installation method unless it's the only option

**Comment by megahead11** [comment]
I believe that might've been from the original readme, but kakaroto has since improved the install method. 
If you have improvements for the readme, I'll welcome any PRs ^^

**Comment by anthonyronda** [comment]
I looked at the GitLab wiki and decided it's not worth working off of what's there

We could likely write more concise usage information of some form, as well as a video

I will reach out to the Japanese Foundry Discord community to see if they have thoughts

**Comment by p4535992** [comment]
The ticket can be closed
