### ISSUE TITLE
[Suggestion] Polyglot Compatibility

### ISSUE THREAD

**Issue by MrVauxs** [League-of-Foundry-Developers/fvtt-module-theatre#43]
**Suggestion:** Support Polyglot's languages and fonts in Theatre Inserts

**Why should this be added:** Allows players and DMs to use Theatre Inserts without making Polyglot's ability to disguise the messages meaningless due to it showing the pure message.

**Comment by mclemente** [comment]
I'm the dev of Polyglot and just found this issue while I was working on compatibility lol
Anyways, all you need is to add the following on line 559 of `theatre_main.js`
```js
if (window.polyglot) {
      const lang = chatData.flags.polyglot.language;
      if (!polyglot.polyglot.known_languages.has(lang)) {
        if (lang != polyglot.polyglot.defaultLanguage) insertFontType = polyglot.polyglot._getFontStyle(lang).slice(5);
        textContent = polyglot.polyglot.scrambleString(textContent, chatData._id, lang);
      }
    }
```
I'll send a PR so it gets added to the module.

**Comment by megahead11** [comment]
Added in latest release! Thanks mclemente!
