### ISSUE TITLE
Text not Displaying under Inserts or in Narrator Mode

### ISSUE THREAD

**Issue by anciet2** [League-of-Foundry-Developers/fvtt-module-theatre#48]
I've attempted to try and get the text to display correctly, even creating a new world (FVTT 0.8.8 & 0.8.9) but cannot get text to display under inserts or in the center of the screen as Narrator.

Everything else seems to be working correctly: typing indicators, emotion animations, inserts sliding in and out of the scene.

**Comment by megahead11** [comment]
Interesting. I think something in the latest PR might have broken the text; I'll have to go investigate it.

**Comment by megahead11** [comment]
Figured it out. Turns out the text doesn't render if polyglot is not enabled.
I have fixed this in the latest patch and will be pushing it very shortly! Thanks :3

**Comment by KoboldCatgirl** [comment]
Sorry to reopen, but this seems to be happening again--Polyglot is directly incompatible with the Stage functioning correctly. As in, if I have Polyglot enabled, I see all the symptoms OP posted about.
