### ISSUE TITLE
Stage expressions don't save using Pathfinder 1

### ISSUE THREAD

**Issue by Edulat** [League-of-Foundry-Developers/fvtt-module-theatre#59]
Whenever I open up an actor, I am unable to save the expressions I've assigned to them. The main expression saves, but any with an emote are immediately wiped upon restarting the world/foundry itself.

**Comment by megahead11** [comment]
Fixed by later PF1 updates

**Comment by Edulat** [comment]
Doesn't seem to be fixed.
Foundry version is 0.8.9.
Pathfinder 1e version is 0.79.10
Theatre inserts version is 1.20.4.

https://user-images.githubusercontent.com/92209120/145947875-b16bafc0-762c-4461-a180-3f59a5c4ccc2.mp4


Video of the bug in action attached here.

**Comment by megahead11** [comment]
Reproduced; going to investigate something in the PF1 system
