### ISSUE TITLE
Cant add an actor to the stage

### ISSUE THREAD

**Issue by west61224** [League-of-Foundry-Developers/fvtt-module-theatre#72]
The right-click menu when selecting an actor is not working on Foundry 9.238 while theatre is active. This error prevents the user from adding an actor to the stage and other actions like deleting, exporting, or changing access permissions of actors.

The console outputs the following message when right-clicking an actor:

```
theatre_main.js:636 Uncaught TypeError: Cannot read property 'data' of undefined
[Detected 1 package: theatre]
    at getActorData (theatre_main.js:636)
    at Object.condition (theatre_main.js:641)
    at ContextMenu.render (foundry.js:43494)
    at HTMLLIElement.<anonymous> (foundry.js:43437)
    at HTMLElement.dispatch (jquery.min.js:2)
    at HTMLElement.v.handle (jquery.min.js:2)
```
![VnGQ1faIZ1](https://user-images.githubusercontent.com/49492395/147288539-5dfcab7f-e9cb-4a5e-9638-1bc900feb594.gif)

This case could be a duplicate of issue #68, but I am not entirely sure if it is the same error.

**Comment by megahead11** [comment]
Theatre is not compatible with v9 yet, but there is a branch thats being tested. That being said, compatibility should be fixed very soon :3

**Comment by west61224** [comment]
Hi, thanks for the quick response glad to know that support for v9 is in the works.

I was able to add an actor to the stage using a simple script macro. I will leave the macros here if someone has the same problem while support for v9 arrives. Just select an actor and activate the macro. It should stage the actor, and everything seems to work fine.

```
//add actor to the stage
Theatre.addToNavBar(actor.data)
```
```
//remove actor from the stage
Theatre.removeFromNavBar(actor.data)
```
Thanks again for the response!
