### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [League-of-Foundry-Developers/fvtt-module-theatre#75]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by megahead11** [comment]
That's odd. I thought I updated the module.json recently to account for this. I'll have to go take a look at what happened.

**Comment by megahead11** [comment]
What version of the module are you using? The one in the release and in the repo has 9 as its compatible version (as opposed to 0.0.9)

**Comment by brunocalado** [comment]
> What version of the module are you using? The one in the latest release and in the repo has 9 as its compatible version (as opposed to 0.0.9)

I was suggeting just replace "compatibleCoreVersion": "9.236" by "compatibleCoreVersion": "9". This will remove the warning for all builds from v9

**Comment by anthonyronda** [comment]
League admins still need to make it show as V9 compatible on the admin panel

**Comment by p4535992** [comment]
The ticket can be closed
