### ISSUE TITLE
Can't right click on an actor in the actor tab

### ISSUE THREAD

**Issue by Kilarn** [League-of-Foundry-Developers/fvtt-module-theatre#82]
Hi,

Quite a strange issue, but I can't right click on any actor which are in the actor tab.
I can still right click on scenes, journal entries, ...

When I deactivate all modules, the bug is still there.

Foundry Version 9.245

Is it a compatibility issue with the last Foundry version?

Thanks!

**Comment by Kilarn** [comment]
It seems the issue was already reported in [ Cant add an actor to the stage #72 ](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/issues/72#issue-1088025218), but it's not yet solved.

**Comment by megahead11** [comment]
What system are you running it in? The v9 update should have fixed this a little ago.

**Comment by Kilarn** [comment]
Wow, that's strange. The installed module version was the 1.17. I updated it right now to 2.0.3 by clicking on update.

Don't know why the latest version was not installed directly. I close the issue then.
