### ISSUE TITLE
BUG : Emote config text error

### ISSUE THREAD

**Issue by jbblily** [League-of-Foundry-Developers/fvtt-module-theatre#96]
![image](https://user-images.githubusercontent.com/18694887/164982921-5887e86b-b956-43d5-b850-86333afbe762.png)

All texts are not localized properly... 
No module enabled.

**Comment by megahead11** [comment]
Hi! 
This is indeed a bug that popped up with the last update. We're gonna see if there was something that might've gotten accidentally deleted with the last PR, since a couple of strings were changed.
Are there any other broken localization strings aside from the emote menu?
